import { randomUUID } from 'node:crypto';
import { db } from '../config/database.js';

export class EngagementRepository {
  async donations(userId: string) { const { rows } = await db.query('SELECT id, amount_cents AS "amountCents", frequency, anonymous, project_id AS "projectId", created_at AS "createdAt", status FROM donations WHERE user_id = $1 ORDER BY created_at DESC', [userId]); return rows; }
  async directory(filters: { country?: string; city?: string; sector?: string; skill?: string }) { const values: string[] = []; const where = ['u.directory_visible = TRUE']; const add = (sql: string, value?: string) => { if (value?.trim()) { values.push(value.trim()); where.push(sql.replace('?', `$${values.length}`)); } }; add('u.country = ?', filters.country); add('n.city ILIKE ?', filters.city ? `%${filters.city}%` : undefined); add('n.sector ILIKE ?', filters.sector ? `%${filters.sector}%` : undefined); add('$? = ANY(n.skills)', filters.skill); const { rows } = await db.query(`SELECT u.id AS "userId", u.first_name AS "firstName", u.last_name AS "lastName", u.country, n.city, n.sector, n.skills FROM networking_profiles n JOIN users u ON u.id = n.user_id WHERE ${where.join(' AND ')} ORDER BY u.first_name LIMIT 100`, values); return rows; }
  async updateProfile(userId: string, input: { visible: boolean; city?: string; sector?: string; skills?: string[] }) { const { rows } = await db.query('INSERT INTO networking_profiles (user_id, city, sector, skills, visibility) VALUES ($1,$2,$3,$4,$5) ON CONFLICT (user_id) DO UPDATE SET city = EXCLUDED.city, sector = EXCLUDED.sector, skills = EXCLUDED.skills, visibility = EXCLUDED.visibility, updated_at = NOW() RETURNING user_id AS "userId", city, sector, skills, visibility', [userId, input.city ?? null, input.sector ?? null, input.skills ?? [], JSON.stringify({ visible: input.visible })]); await db.query('UPDATE users SET directory_visible = $2 WHERE id = $1', [userId, input.visible]); return rows[0]; }
  async requestConnection(requesterId: string, recipientId: string) { if (requesterId === recipientId) throw new Error('Cannot connect to self'); const { rows } = await db.query('INSERT INTO networking_requests (id, requester_id, recipient_id, status) VALUES ($1,$2,$3,\'pending\') ON CONFLICT (requester_id, recipient_id) DO UPDATE SET status = \'pending\' RETURNING id, status, created_at AS "createdAt"', [randomUUID(), requesterId, recipientId]); return rows[0]; }
  async notifications(userId: string) { const { rows } = await db.query('SELECT id, type, title, body, read_at AS "readAt", created_at AS "createdAt" FROM notifications WHERE user_id = $1 ORDER BY created_at DESC LIMIT 100', [userId]); return rows; }
  async registerDevice(userId: string, input: { token: string; platform: string; preferences: Record<string, boolean> }) { await db.query('INSERT INTO device_tokens (id, user_id, token, platform, preferences) VALUES ($1,$2,$3,$4,$5) ON CONFLICT (token) DO UPDATE SET user_id = EXCLUDED.user_id, platform = EXCLUDED.platform, preferences = EXCLUDED.preferences', [randomUUID(), userId, input.token, input.platform, JSON.stringify(input.preferences)]); return { registered: true }; }
}
